import {
  ArrowLeftRight,
  Bot,
  Brain,
  Car,
  CreditCard,
  Disc3,
  Fingerprint,
  Globe,
  Landmark,
  LayoutDashboard,
  MessagesSquare,
  PhoneCall,
  Store,
  Target,
  Users,
  Wallet,
} from "lucide-react";
import type { ProfileCardData } from "@/components/product/profile-card";

export const productProfileCards: Record<string, ProfileCardData> = {
  intelligence: {
    initials: "AA",
    title: "Intent record",
    subtitle: "Normalized · ID 8842-AA",
    metricLabel: "Intent score",
    metricValue: "92",
    metricStatus: "High · in-market",
    metricPercent: 92,
    meta: ["4 sources", "SHA-256 export"],
    signals: [
      { icon: Globe, label: "Pixel event enriched · prime band", time: "now", hot: true },
      { icon: Brain, label: "Segment tagged · special finance", time: "2m" },
      { icon: Target, label: "Audience exported · Meta CAPI", time: "8m" },
      { icon: Fingerprint, label: "CRM match · duplicate merged", time: "14m" },
    ],
    channels: [
      { icon: Globe, label: "Pixel" },
      { icon: Brain, label: "Engine" },
      { icon: Target, label: "Ads" },
      { icon: Store, label: "CRM" },
    ],
    nextAction: "Push to BDC queue",
  },

  "super-pixel": {
    initials: "JM",
    title: "Unified shopper profile",
    subtitle: "Identity resolved · ID 8842-AA",
    metricLabel: "Intent score",
    metricValue: "92",
    metricStatus: "High · in-market",
    metricPercent: 92,
    meta: ["3 sources", "Prime band"],
    signals: [
      { icon: Globe, label: "Viewed F-150 XLT · 3rd visit", time: "now", hot: true },
      { icon: Car, label: "Credit app started · subprime", time: "4m" },
      { icon: Fingerprint, label: "Income enriched · $84k HH", time: "11m" },
      { icon: Store, label: "AutoTrader click · VDP match", time: "22m" },
    ],
    channels: [
      { icon: Globe, label: "Web" },
      { icon: Store, label: "Market" },
      { icon: PhoneCall, label: "Phone" },
      { icon: Fingerprint, label: "Enrich" },
    ],
    nextAction: "Route warm lead",
  },

  "bdc-copilot": {
    initials: "MR",
    title: "Warm handoff ready",
    subtitle: "AI qualified · SMS verified",
    metricLabel: "Handoff score",
    metricValue: "87",
    metricStatus: "Book today",
    metricPercent: 87,
    meta: ["Voice + SMS", "0 cold calls"],
    signals: [
      { icon: Bot, label: "AI call completed · buyer said yes", time: "now", hot: true },
      { icon: PhoneCall, label: "Warm transfer queued · sales", time: "1m" },
      { icon: MessagesSquare, label: "Appointment confirmed · 2pm", time: "6m" },
      { icon: Globe, label: "Super Pixel · F-150 intent", time: "18m" },
    ],
    channels: [
      { icon: PhoneCall, label: "Voice" },
      { icon: MessagesSquare, label: "SMS" },
      { icon: Globe, label: "Chat" },
      { icon: Bot, label: "AI" },
    ],
    nextAction: "Manager approve transfer",
  },

  "marketplace-copilot": {
    initials: "FB",
    title: "Marketplace conversation",
    subtitle: "Dealer Solo · thread open",
    metricLabel: "Reply score",
    metricValue: "94",
    metricStatus: "Book next step",
    metricPercent: 94,
    meta: ["2-click post", "AI draft ready"],
    signals: [
      { icon: Store, label: "2019 Silverado posted · high demand", time: "now", hot: true },
      { icon: MessagesSquare, label: "Buyer replied · price question", time: "3m" },
      { icon: Bot, label: "AI draft ready · dealer review", time: "3m" },
      { icon: Target, label: "Test drive offered · pending", time: "9m" },
    ],
    channels: [
      { icon: Store, label: "Market" },
      { icon: MessagesSquare, label: "Chat" },
      { icon: Bot, label: "Copilot" },
      { icon: Globe, label: "Inventory" },
    ],
    nextAction: "Send suggested reply",
  },

  "trade-copilot": {
    initials: "TC",
    title: "Trade acquisition",
    subtitle: "SMS verified · desk payload",
    metricLabel: "Range confidence",
    metricValue: "88",
    metricStatus: "Desk review",
    metricPercent: 88,
    meta: ["KBB + market", "Proof attached"],
    signals: [
      { icon: ArrowLeftRight, label: "2018 Camry range · $11.2–12.4k", time: "now", hot: true },
      { icon: Car, label: "Carvana offer uploaded · proof OK", time: "5m" },
      { icon: PhoneCall, label: "OTP verified · callable lead", time: "7m" },
      { icon: Target, label: "Replacement intent · SUV locate", time: "12m" },
    ],
    channels: [
      { icon: ArrowLeftRight, label: "Trade" },
      { icon: Car, label: "Range" },
      { icon: PhoneCall, label: "Verify" },
      { icon: Store, label: "Desk" },
    ],
    nextAction: "Appraiser review proof",
  },

  "buyer-center-ai": {
    initials: "BC",
    title: "Acquisition candidate",
    subtitle: "Buy Box match · listing scored",
    metricLabel: "Buy Box score",
    metricValue: "91",
    metricStatus: "Outreach now",
    metricPercent: 91,
    meta: ["Craigslist", "No duplicate"],
    signals: [
      { icon: Car, label: "2017 Tacoma · under market ask", time: "now", hot: true },
      { icon: Users, label: "Seller contacted · draft sent", time: "8m" },
      { icon: Store, label: "FB Marketplace import · scored", time: "22m" },
      { icon: Target, label: "Margin fit · recon $1,200", time: "31m" },
    ],
    channels: [
      { icon: Store, label: "Market" },
      { icon: Users, label: "Outreach" },
      { icon: Car, label: "Buy Box" },
      { icon: Globe, label: "Feeds" },
    ],
    nextAction: "Schedule inspection",
  },

  "we-finance-usa": {
    initials: "WF",
    title: "Deal gap identified",
    subtitle: "Branded flow · multi-lender",
    metricLabel: "Close probability",
    metricValue: "86",
    metricStatus: "Fund the gap",
    metricPercent: 86,
    meta: ["$4,200 need", "3 lenders"],
    signals: [
      { icon: Wallet, label: "Down payment short · $4,200", time: "now", hot: true },
      { icon: CreditCard, label: "Lender match · 2 offers back", time: "4m" },
      { icon: Landmark, label: "Negative equity bridge flagged", time: "11m" },
      { icon: Globe, label: "Intent activation · in-market", time: "1h" },
    ],
    channels: [
      { icon: Wallet, label: "Cash" },
      { icon: CreditCard, label: "Lenders" },
      { icon: Landmark, label: "Finance" },
      { icon: Globe, label: "Demand" },
    ],
    nextAction: "Present lender offers",
  },

  dealeros: {
    initials: "DO",
    title: "Floor command",
    subtitle: "DealerOS · live status",
    metricLabel: "Action queue",
    metricValue: "14",
    metricStatus: "Need attention",
    metricPercent: 72,
    meta: ["6 warm xfer", "3 overdue"],
    signals: [
      { icon: LayoutDashboard, label: "BDC Command · 6 warm transfers", time: "now", hot: true },
      { icon: Bot, label: "Agent factory · aged SUV campaign live", time: "2m" },
      { icon: Target, label: "Ads Audit · $2.1k waste flagged", time: "9m" },
      { icon: Brain, label: "Ask Copilot · follow-up draft ready", time: "15m" },
    ],
    channels: [
      { icon: LayoutDashboard, label: "Floor" },
      { icon: Bot, label: "AI" },
      { icon: Target, label: "Ops" },
      { icon: Brain, label: "Data" },
    ],
    nextAction: "Approve ranked handoff",
  },

  tredfi: {
    initials: "TF",
    title: "Retail shopper",
    subtitle: "Visualizer · fitment locked",
    metricLabel: "Approval score",
    metricValue: "89",
    metricStatus: "Ready to close",
    metricPercent: 89,
    meta: ["20\" package", "2 offers"],
    signals: [
      { icon: Disc3, label: "Visualizer · 20\" sport package saved", time: "now", hot: true },
      { icon: CreditCard, label: "Financing pre-qualified · 2 lenders", time: "3m" },
      { icon: Store, label: "Counter quote · $2,840 out the door", time: "8m" },
      { icon: Globe, label: "Intent traffic · local campaign", time: "25m" },
    ],
    channels: [
      { icon: Disc3, label: "Visual" },
      { icon: CreditCard, label: "Finance" },
      { icon: Store, label: "Retail" },
      { icon: Globe, label: "Growth" },
    ],
    nextAction: "Close at counter",
  },
};

export function getProductProfileCard(slug: string): ProfileCardData | undefined {
  return productProfileCards[slug];
}
