#!/usr/bin/env bash
# Repair corrupted FORMS_FROM_EMAIL / DEMO_FROM_EMAIL on Vercel.
# Run from project root after fixing .env.local (or pass FORMS_FROM_EMAIL).
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ENV_LOCAL="$ROOT_DIR/.env.local"
DEFAULT_FROM='Audience Activator AI <notifications@audienceactivator.ai>'

if [[ -f "$ENV_LOCAL" ]]; then
  # shellcheck disable=SC1090
  source <(grep -E '^(RESEND_API_KEY|FORMS_FROM_EMAIL|FORMS_TO_EMAIL)=' "$ENV_LOCAL" | sed 's/^/export /')
fi

FORMS_FROM_EMAIL="${FORMS_FROM_EMAIL:-$DEFAULT_FROM}"
FORMS_TO_EMAIL="${FORMS_TO_EMAIL:-james@tredfi.com}"

if [[ -z "${RESEND_API_KEY:-}" ]]; then
  echo "RESEND_API_KEY missing. Set it in .env.local or export it first." >&2
  exit 1
fi

if [[ ! "$FORMS_FROM_EMAIL" =~ @ ]]; then
  echo "FORMS_FROM_EMAIL is invalid: $FORMS_FROM_EMAIL" >&2
  exit 1
fi

cat >"$ENV_LOCAL" <<EOF
# Generated by scripts/fix-resend-from-env.sh
RESEND_API_KEY=${RESEND_API_KEY}
FORMS_FROM_EMAIL=${FORMS_FROM_EMAIL}
FORMS_TO_EMAIL=${FORMS_TO_EMAIL}
DEMO_FROM_EMAIL=${FORMS_FROM_EMAIL}
DEMO_TO_EMAIL=${FORMS_TO_EMAIL}
EOF

echo "Wrote $ENV_LOCAL"

if ! command -v vercel >/dev/null 2>&1; then
  echo "Install Vercel CLI, then re-run this script." >&2
  exit 1
fi

cd "$ROOT_DIR"
for env in production preview development; do
  for name in FORMS_FROM_EMAIL DEMO_FROM_EMAIL FORMS_TO_EMAIL DEMO_TO_EMAIL RESEND_API_KEY; do
    value="${!name}"
    vercel env rm "$name" "$env" --yes 2>/dev/null || true
    printf '%s' "$value" | vercel env add "$name" "$env" >/dev/null
  done
  echo "Synced $env"
done

echo ""
echo "Redeploy, then verify:"
echo "  vercel deploy --prod"
echo "  curl https://www.audienceactivator.ai/api/forms/health"
