#!/usr/bin/env bash
# Configure Resend for demo + Access Pricing forms (local .env.local + Vercel).
#
# Usage:
#   RESEND_API_KEY=re_xxx ./scripts/setup-resend-forms.sh
#   ./scripts/setup-resend-forms.sh   # prompts for API key
#
# Prerequisites:
#   - Resend account with audienceactivator.ai domain verified
#   - vercel CLI logged in (vercel login)
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ENV_LOCAL="$ROOT_DIR/.env.local"

DEFAULT_FROM='Audience Activator AI <notifications@audienceactivator.ai>'
DEFAULT_TO="${FORMS_TO_EMAIL:-james@tredfi.com}"

read -r -p "Resend API key (re_...): " RESEND_API_KEY_INPUT
RESEND_API_KEY="${RESEND_API_KEY:-${RESEND_API_KEY_INPUT}}"
if [[ -z "${RESEND_API_KEY}" ]]; then
  echo "RESEND_API_KEY is required." >&2
  exit 1
fi

read -r -p "From address [${DEFAULT_FROM}]: " FROM_INPUT
FORMS_FROM_EMAIL="${FROM_INPUT:-$DEFAULT_FROM}"

read -r -p "Notification inbox [${DEFAULT_TO}]: " TO_INPUT
FORMS_TO_EMAIL="${TO_INPUT:-$DEFAULT_TO}"

cat >"$ENV_LOCAL" <<EOF
# Generated by scripts/setup-resend-forms.sh
RESEND_API_KEY=${RESEND_API_KEY}
FORMS_FROM_EMAIL=${FORMS_FROM_EMAIL}
FORMS_TO_EMAIL=${FORMS_TO_EMAIL}
DEMO_FROM_EMAIL=${FORMS_FROM_EMAIL}
DEMO_TO_EMAIL=${FORMS_TO_EMAIL}
EOF

echo "Wrote $ENV_LOCAL"

push_env() {
  local name="$1"
  local value="$2"
  for env in production preview development; do
    vercel env rm "$name" "$env" --yes 2>/dev/null || true
    printf '%s' "$value" | vercel env add "$name" "$env" >/dev/null
  done
  echo "  ✓ $name"
}

if command -v vercel >/dev/null 2>&1; then
  echo "Syncing Vercel env (audience-activator-ai)..."
  cd "$ROOT_DIR"
  push_env RESEND_API_KEY "$RESEND_API_KEY"
  push_env FORMS_FROM_EMAIL "$FORMS_FROM_EMAIL"
  push_env FORMS_TO_EMAIL "$FORMS_TO_EMAIL"
  push_env DEMO_FROM_EMAIL "$FORMS_FROM_EMAIL"
  push_env DEMO_TO_EMAIL "$FORMS_TO_EMAIL"
  echo "Done. Redeploy production for changes to take effect:"
  echo "  vercel deploy --prod"
else
  echo "Vercel CLI not found — set these in Project → Settings → Environment Variables:"
  echo "  RESEND_API_KEY"
  echo "  FORMS_FROM_EMAIL (or DEMO_FROM_EMAIL)"
  echo "  FORMS_TO_EMAIL (or DEMO_TO_EMAIL)"
fi

echo ""
echo "Verify after deploy:"
echo "  curl https://www.audienceactivator.ai/api/forms/health"
